### ISSUE TITLE
Couchbase Sink Connector multiple parameters in couchbase.document.id

### ISSUE THREAD

**Issue by HafizHussain31** [couchbase/kafka-connect-couchbase#39]
I am exploring sink connector where I found couchbase.document.id is accepting a single parameter. I am wondering if we can do give multiple fields here in the same order we give topic.to.collection field. 

So that, every collection will have document id received from unique field in the kafka message.

For eg, 
if couchbase.topic.to.collection="topic1=collection1,topic2=collection2"
then couchbase.document.id="collection1=/after/id1,collection2=/after/id2"

**Comment by dnault** [comment]
Hi @HafizHussain31 ! Thanks for taking a look at the connector.

As you have seen, that's not something the connector currently supports. I'll bring this feature request to the attention of our product manager.

In the meantime, you could explore transforming the Kafka record so the record ID is the same as the desired Couchbase document ID. You could do this:

* When publishing the document.
* With a Kafka Stream that changes the document ID based on the document fields.
* With a Single Message Transform (SMT) applied to the sink connector.

If you decide to explore that third suggestion, there's an example of how to write a custom SMT here: https://github.com/couchbase/kafka-connect-couchbase/tree/master/examples/custom-extensions

Thanks,
David

**Comment by dnault** [comment]
CC: PM @vishaldhiman22

**Comment by HafizHussain31** [comment]
This is something I want to make it work on the connector itself.

I understand it might take some time to develop, I went through the code and I would like to contribute through this feature. Let me know if I may!! 

I can sit through the weekend and raise a PR.

**Comment by HafizHussain31** [comment]
Thanks David,

I signed the agreement. I'll check, push the code once it is done. Will keep you posted. 

Thanks,
Hafiz

**Comment by HafizHussain31** [comment]
Hi David, 

I implemented the feature and raised PR. Please review. 

Regards
Hafiz

**Comment by dnault** [comment]
Hi @HafizHussain31 ,

We're having trouble correlating your contribution with your Gerrit account. Can you please add another email address to your Gerrit account -- the gmail address associated with your commits?

* Log into Gerrit, then click the gear icon in the top right.
* From the left sidebar, select "Email Addresses".
* Look for "New email address" and type the address there.
* Click the "Send verification" button.
* Check your email, and look for a message with the final step.

Thanks!

**Comment by HafizHussain31** [comment]
Hi David,

Following is my gmail id with which I raised PR hhafizhussain@gmail.com. I used the same email id to create Gerrit account as well. 

![image](https://github.com/user-attachments/assets/53214eb9-fc93-4c8d-86fc-faa25b98f1ab)

**Comment by dnault** [comment]
Thanks @HafizHussain31 . We're ready to proceed. As mentioned earlier, it might take a while to review the code based on internal priorities.

**Comment by HafizHussain31** [comment]
Hi @dnault, just wanted to check if there is any update on the PR.

Thanks.

**Comment by dnault** [comment]
Hi @HafizHussain31 Thanks for the nudge. I made a few minor adjustments and ported the PR over to Gerrit: https://review.couchbase.org/c/kafka-connect-couchbase/+/218785

Are you okay with being credited by your GitHub account name, or would you prefer something else?

**Comment by dnault** [comment]
Done. The new config property will be available in 4.2.4, to be released any day now.

The release is on a tight schedule, so I'll go ahead and credit you by GitHub username. If you have a different preference, let me know and we'll update the release notes accordingly.

Thank you again for this contribution!

Cheers,
David

**Comment by HafizHussain31** [comment]
Hi David,

I am glad I'm able to help. I would like to contribute more to this project
if you have any enhancements to make or got any issue to fix. Please feel
free to reach out to me.

Also, you can go ahead with my github username, my full name is *Hafiz
Hussain Haroon Rasheed*, if you want to mention it anywhere.

Regards
Hafiz
