### ISSUE TITLE
Publish full package  to Maven central

### ISSUE THREAD

**Issue by yeikel** [couchbase/kafka-connect-couchbase#40]
Hi team, 

Would it be possible to publish the full artifact you publish to https://packages.couchbase.com/ to Maven central as well? 

The mirror `https://packages.couchbase.com` does not behave like a typical maven mirror making it very difficult to mirror in a corporate environment 

Thank you

**Comment by dnault** [comment]
Hi @yeikel !

The same binaries are published to Confluent Hub. Is that any easier for you to access/mirror?

https://www.confluent.io/hub/couchbase/kafka-connect-couchbase

Thanks,
David

**Comment by yeikel** [comment]
Hi @dnault 

The Confuent Hub links do seem to follow any predictable format. For example, I ignore if `d2p6pa21dvn84.cloudfront` is a fixed value or dynamic depending on infra details. 

Beyond that and more importantly,  it seems that their cluster does not support directory listing which makes it a bit challenging to discover new versions. Both `https://d2p6pa21dvn84.cloudfront.net/api/plugins/couchbase/kafka-connect-couchbase/` and `https://d2p6pa21dvn84.cloudfront.net/api/plugins/couchbase/kafka-connect-couchbase/versions` return access denied

**Comment by dnault** [comment]
I would like to get a better understanding of the issue, and the limitations of your corporate environment.

Can you access packages.couchbase.com from your corporate environment?

If not, could your corporate proxy be configure to allow it?

Is there something special about Maven Central that makes it accessible in your corporate environment, or are you just keen on mirroring the connector distribution, and you already have a scheme in place for mirroring Maven repositories?

Beyond thIs there a particular reason you want the connector to be in something structured like a maven repository?

Thanks,
David

**Comment by yeikel** [comment]
> Can you access packages.couchbase.com from your corporate environment?

As it turns out, I discovered that it is possible to mirror that too

> Beyond thIs there a particular reason you want the connector to be in something structured like a maven repository?

Generally speaking, it makes version discovery with tools like `dependabot` possible. I am currently using the JAR as well(to extend the connector) so I am covered and this is no longer needed(

Thank you!
